"""Add AI proctoring and stress detection tables

Revision ID: 3e6b3d4f2531
Revises: 08e479978e4f
Create Date: 2025-10-05 20:34:52.611223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6b3d4f2531'
down_revision = '08e479978e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proctoring_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('face_detected', sa.Boolean(), nullable=True),
    sa.Column('multiple_faces', sa.Boolean(), nullable=True),
    sa.Column('mobile_detected', sa.Boolean(), nullable=True),
    sa.Column('suspicious_activity', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('detected_emotion', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stress_log')
    op.drop_table('proctoring_log')
    # ### end Alembic commands ###
