"""Add video_thumbnail to RecommendedVideo

Revision ID: 405f89d45e9f
Revises: af6a98752b11
Create Date: 2025-10-13 19:52:41.053012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405f89d45e9f'
down_revision = 'af6a98752b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_thumbnail', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_video', schema=None) as batch_op:
        batch_op.drop_column('video_thumbnail')

    # ### end Alembic commands ###
