"""Add eye_gaze_away to ProctoringLog

Revision ID: 8f03f371488f
Revises: fb1a4e942b71
Create Date: 2025-10-09 21:53:39.492393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f03f371488f'
down_revision = 'fb1a4e942b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proctoring_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_gaze_away', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proctoring_log', schema=None) as batch_op:
        batch_op.drop_column('eye_gaze_away')

    # ### end Alembic commands ###
