"""Full migration: add all new fields and tables

Revision ID: af6a98752b11
Revises: 39f599fe6174
Create Date: 2025-10-13 19:16:51.386853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6a98752b11'
down_revision = '39f599fe6174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followup_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('student_answer', sa.String(length=1), nullable=True))
        batch_op.create_foreign_key('fk_followup_attempt_id', 'test_attempt', ['attempt_id'], ['id'])

    with op.batch_alter_table('recommended_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_video', schema=None) as batch_op:
        batch_op.drop_column('video_summary')

    with op.batch_alter_table('followup_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_followup_attempt_id', type_='foreignkey')
        batch_op.drop_column('student_answer')
        batch_op.drop_column('attempt_id')

    # ### end Alembic commands ###
