"""Make test duration dynamic and required

Revision ID: bb282bf44487
Revises: da7e7becf779
Create Date: 2025-09-30 23:20:24.459090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb282bf44487'
down_revision = 'da7e7becf779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
