"""Fix StudentAnswer marked_for_review and JSON fields

Revision ID: cb132dceaf52
Revises: dba304391410
Create Date: 2025-09-30 13:54:33.945646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb132dceaf52'
down_revision = 'dba304391410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_for_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.drop_column('marked_for_review')

    # ### end Alembic commands ###
