"""Changes is Followup Assigenment

Revision ID: d29bb2bd0663
Revises: 44aa3548be9e
Create Date: 2025-10-26 20:38:30.848388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29bb2bd0663'
down_revision = '44aa3548be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followup_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_hint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))

    with op.batch_alter_table('student_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_time', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('followup_progress', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('learning_gaps', sa.JSON(), nullable=True))

    with op.batch_alter_table('student_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wrong_questions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('followup_assigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('followup_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('remaining_weak_topics', sa.JSON(), nullable=True))

    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_time', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weak_topics_after_followup', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.drop_column('weak_topics_after_followup')
        batch_op.drop_column('topic_time')

    with op.batch_alter_table('student_review', schema=None) as batch_op:
        batch_op.drop_column('remaining_weak_topics')
        batch_op.drop_column('followup_results')
        batch_op.drop_column('followup_assigned')
        batch_op.drop_column('wrong_questions')

    with op.batch_alter_table('student_analytics', schema=None) as batch_op:
        batch_op.drop_column('learning_gaps')
        batch_op.drop_column('followup_progress')
        batch_op.drop_column('topic_time')

    with op.batch_alter_table('followup_assignment', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('ai_hint')

    # ### end Alembic commands ###
