"""Add end_time to TestAttempt

Revision ID: da7e7becf779
Revises: cb132dceaf52
Create Date: 2025-09-30 22:19:52.405425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7e7becf779'
down_revision = 'cb132dceaf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
