"""Added YOLO proctoring fields and summary

Revision ID: fb1a4e942b71
Revises: 3e6b3d4f2531
Create Date: 2025-10-09 19:04:31.667379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1a4e942b71'
down_revision = '3e6b3d4f2531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proctoring_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('total_warnings', sa.Integer(), nullable=True),
    sa.Column('total_faces_detected', sa.Integer(), nullable=True),
    sa.Column('total_mobile_detections', sa.Integer(), nullable=True),
    sa.Column('total_window_shifts', sa.Integer(), nullable=True),
    sa.Column('last_action', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctoring_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_switch_detected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('warning_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('system_message', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('auto_submitted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_submitted_due_to_violation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempt', schema=None) as batch_op:
        batch_op.drop_column('auto_submitted_due_to_violation')

    with op.batch_alter_table('proctoring_log', schema=None) as batch_op:
        batch_op.drop_column('auto_submitted')
        batch_op.drop_column('system_message')
        batch_op.drop_column('warning_level')
        batch_op.drop_column('window_switch_detected')

    op.drop_table('proctoring_summary')
    # ### end Alembic commands ###
